prompt --application/pages/page_00021
begin
--   Manifest
--     PAGE: 00021
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.0'
,p_default_workspace_id=>5563191275573624319
,p_default_application_id=>80528
,p_default_id_offset=>0
,p_default_owner=>'WKSP_TEST99'
);
wwv_flow_api.create_page(
 p_id=>21
,p_user_interface_id=>wwv_flow_api.id(5725100070607402811)
,p_name=>'Create Event'
,p_alias=>'CREATE-EVENT'
,p_step_title=>'Create Event'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_last_updated_by=>'MANALISHAH2899@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20210523052041'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(6842648534048077749)
,p_plug_name=>'Report 1'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(5725008301356402766)
,p_plug_display_sequence=>10
,p_plug_display_point=>'BODY'
,p_query_type=>'TABLE'
,p_query_table=>'EVENTS_VIEW'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'Report 1'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(6842648917664077749)
,p_name=>'Report 1'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_download_formats=>'CSV:HTML:EMAIL:XLSX:PDF:RTF'
,p_detail_link=>'f?p=&APP_ID.:22:&SESSION.::&DEBUG.:RP:P22_EVENTID:\#EVENTID#\'
,p_detail_link_text=>'<span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>'
,p_owner=>'MANALISHAH2899@GMAIL.COM'
,p_internal_uid=>6842648917664077749
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842649069403077750)
,p_db_column_name=>'EVENTID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Eventid'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842649442933077750)
,p_db_column_name=>'EVENTDESCRIPTION'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Eventdescription'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842649821602077750)
,p_db_column_name=>'EVENTDATE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Eventdate'
,p_column_type=>'DATE'
,p_column_alignment=>'CENTER'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842650218783077751)
,p_db_column_name=>'EVENTTIME'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Eventtime'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842650628120077751)
,p_db_column_name=>'ORGANISER'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Organiser'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842651049889077751)
,p_db_column_name=>'ORGANISERCONTACTEMAIL'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Organisercontactemail'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842651408469077751)
,p_db_column_name=>'BOOKABLE'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Bookable'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842651885817077752)
,p_db_column_name=>'CAMPUSID'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Campusid'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(6842652292893077752)
,p_db_column_name=>'CAMPUS'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Campus'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(7251823995809145957)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'72518240'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'EVENTID:EVENTDESCRIPTION:EVENTDATE:EVENTTIME:ORGANISER:ORGANISERCONTACTEMAIL:BOOKABLE:CAMPUSID:CAMPUS'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(6842653466350077769)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(6842648534048077749)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(5725075401513402798)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:22:&SESSION.::&DEBUG.:22'
);
wwv_flow_api.component_end;
end;
/
